import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const proximaNovaRegular = localFont({
  src: "./fonts/Proxima Nova Regular.ttf",
  variable: "--font-proxima-nova-regular",
  weight: "400",
  style: "normal",
});

// Define Proxima Nova Bold
const proximaNovaBold = localFont({
  src: "./fonts/Proxima Nova Bold.ttf",
  variable: "--font-proxima-nova-bold",
  weight: "700",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${proximaNovaRegular.variable} ${proximaNovaBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
