import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Define Proxima Nova Regular
const proximaNovaRegular = localFont({
  src: "./fonts/proximanova_regular.ttf",
  variable: "--font-proxima-nova-regular",
  weight: "400",
});

// Define Proxima Nova Bold
const proximaNovaBold = localFont({
  src: "./fonts/proximanova_bold.otf",
  variable: "--font-proxima-nova-bold",
  weight: "700",
});

// Define Proxima Nova Black
const proximaNovaBlack = localFont({
  src: "./fonts/proximanova_black.ttf",
  variable: "--font-proxima-nova-black",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${proximaNovaRegular.variable} ${proximaNovaBold.variable} ${proximaNovaBlack.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
